# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2020-01-25 12:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('subcity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'verbose_name_plural': 'Episodes'},
        ),
        migrations.AlterModelOptions(
            name='show',
            options={'verbose_name_plural': 'Shows'},
        ),
        migrations.AddField(
            model_name='show',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 1, 25, 12, 43, 33, 619340, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
